---
title: Mini-rotations - Trophic overyielding and infection dynamics
format: 
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
author:
  - name: Cole Brookson
abstract: |
  Working through ideas for the mini-rotations project
date: last-modified
bibliography: references.bib
csl: ecology-letters.csl
citation:
  container-title: Earth and Space Science
number-sections: true
jupyter: julia-1.10
---

\section{Background}

Previous work has shown that the coexistence of a pair or mixture of species can reach higher abundance than the species with the highest carrying capacity [@loreau_does_2004; @poisot_trophic_2013]. This idea of "transgressive overyielding" is the basis for much work on biodiversity-ecosystem functioning relationships (BEF) [i.e., @schmid_biodiversity_2008]. Some research has suggested approaches to linking this concept to disease dynamics [@johnson_frontiers_2015], however, few studies have explicitly developed theory to this effect. Noteably @sieben_quantifying_2022 and others have provided elegant frameworks for considering competition and coexistence from the perspective of parasites themselves existing in both between- and within-host frameworks. However, \textbf{what effects do infection dynamics have on transgressive overyielding?} Is it possible that the inclusion of pathogen dynamics into classic models of competition would change the conditions under which transgressive overyielding is founded? If so, what is the relation of the virulence of the infection and the basic reproductive number $\mathcal{R_0}$?

\section{Methods}

We start from the assumption of two species competing, in a Lotka-Volterra model. We use the form of @abrams_competition_2022[pg. 39], which includes terms for both inter- and intra-specific competition. We then have

\begin{equation}
  \label{eqn:simple-lv-1}
  \frac{dN_1}{dt} = N_1(r_1 - \alpha_{11}N_1 - \alpha_{12}N_2)
\end{equation} \begin{equation}
  \label{eqn:simple-lv-2}
  \frac{dN_2}{dt} = N_2(r_2 - \alpha_{21}N_1 - \alpha_{22}N_2)
\end{equation}

The relation to the original generalized Lotka-Volterra model (as pointed out by Abrams 2022) is that $\alpha_{ii} = \frac{1}{K_i}$ and $\alpha_{ij} = \frac{\alpha_{ij}}{K_i}$. 

Further and related, we can imagine one of these species becoming infected with a generalized pathogen. The closed population of that species now can be thought of as being described by a standard compartment model. That is, the number of individuals in $N_1$ can be thought of as divided into individuals that are susceptible, $S_1$, infected $I_1$, and recovered $R_1$ such that 

\begin{equation} 
\label{eqn:sum-sir}
  N_1 = S_1 + I_1 + R_1
\end{equation}

Further, we can then think of these dynamics as being described by a classic $SIR$ model with the dynamics given by:

\begin{equation}
\label{eqn:basic-sir-s}
  \frac{dS}{dt} = - \beta S I + \delta R 
\end{equation}

\begin{equation}
\label{eqn:basic-sir-i}
  \frac{dI}{dt} = \beta S I - \gamma I 
\end{equation}

\begin{equation}
\label{eqn:basic-sir-r}
  \frac{dR}{dt} = \gamma I - \delta R
\end{equation}

\subsection{Transgressive Overyielding}

To understand how the incorporation of infection dynamics may affect the conditions under which transgressive overyielding happens, our goals are to: 

1) Re-derive an expression for transgressive overyielding from the inter- and intra-specific version of the GLV (Eqns \ref{eqn:simple-lv-1} \ref{eqn:simple-lv-2})
2) Re-state this expression in terms of the infection parameters that will affect the inter-specifi competition 
3) Assess the assumption of non-linear growth on these expressions
4) 

\begin{table}[hpt]
\centering
\begin{tabular}{ |m{3cm}||m{10cm}|}
     \hline
     \multicolumn{2}{|c|}{Model Parameters} \\
     \hline
     \textbf{Term} & \textbf{Description} \\
     \hline
     $N_i$ & Abundance of species $i$ \\
     $r_i$ & Growth rate of species $i$ \\
     $\alpha_{ii}$ & Intraspecific competition within species $i$ \\
     $\alpha_{ij}$ & Interspecific competition between species $i$ and $j$ \\
     $S_i$ & Number of susceptible individuals in population $i$ \\
     $I_i$ & Number of infected individuals in population $i$ \\
     $R_i$ & Number of recovered individuals in population $i$ \\
     $\beta$ & Rate at which susceptible individuals become infected \\
     $\delta$ & Rate at which recovered individuals lose their immunity and become susceptible again \\
     $\gamma$ & Rate at which the infected individuals recover from infection \\
     \hline
\end{tabular}
\caption{Parameter values for our model systems}
\label{table:parameters}
\end{table}


```{dot}
digraph G {
  layout=neato
  run->intr;
  intr->run
}
```

\section{References}
